version: "3.3"

services:

  csvserver:

    image: "infracloudio/csvserver:latest"

    ports:

      - "9393:9300"

    volumes:

      - /home/inputdata:/csvserver/inputdata

    environment:

      CSVSERVER_BORDER: Orange

  prometheus:
    container_name: prometheus
    image: "prom/prometheus:v2.22.0"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
    - '--config.file=/etc/prometheus/prometheus.yaml'


















    

    
